import { playwright } from '@vitest/browser-playwright'
import { defineConfig } from 'vite-plus'

const PLANET_ENTRIES = [
  'earth',
  'jupiter',
  'mars',
  'mercury',
  'moon',
  'neptune',
  'pluto',
  'saturn',
  'sky',
  'sun',
  'titan',
  'uranus',
  'venus',
] as const

export default defineConfig({
  fmt: {
    // next-env.d.ts is regenerated by Next on every build.
    ignorePatterns: ['website/.next/**', 'website/out/**', 'website/next-env.d.ts'],
    semi: false,
    singleQuote: true,
  },
  lint: {
    ignorePatterns: ['dist/**', 'website/.next/**', 'website/out/**'],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    plugins: ['typescript', 'react'],
  },
  pack: {
    // Rolldown drops top-level directives from non-entry modules, and every
    // planet entry is a re-export barrel. Re-attach the directive to each JS
    // chunk so React Server Components treat the package as client-only.
    banner: { js: "'use client'" },
    deps: {
      neverBundle: ['react', 'react-dom', 'react/jsx-runtime'],
    },
    dts: true,
    entry: {
      index: 'src/index.ts',
      ...Object.fromEntries(
        PLANET_ENTRIES.map((planet) => [`${planet}/index`, `src/${planet}/index.ts`]),
      ),
    },
    format: ['esm'],
    publint: true,
    sourcemap: true,
  },
  staged: {
    '*.{css,js,json,jsx,md,mjs,ts,tsx,yaml,yml}': 'vp check --fix',
  },
  test: {
    projects: [
      {
        test: {
          exclude: ['src/**/*.browser.test.{ts,tsx}'],
          include: ['src/**/*.test.{ts,tsx}'],
          name: 'unit',
        },
      },
      {
        test: {
          // Real Chromium with SwiftShader so every planet's GLSL is compiled
          // and presented at least once. Requires `npx playwright install chromium`.
          browser: {
            enabled: true,
            headless: true,
            instances: [{ browser: 'chromium' }],
            provider: playwright({
              launchOptions: {
                args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
              },
            }),
            screenshotFailures: false,
          },
          include: ['src/**/*.browser.test.{ts,tsx}'],
          name: 'browser',
          testTimeout: 60_000,
        },
      },
    ],
  },
})
